-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 02:14:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projecto_duo_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projecto_duo_db` ;

-- -----------------------------------------------------
-- Schema projecto_duo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projecto_duo_db` DEFAULT CHARACTER SET utf8 ;
USE `projecto_duo_db` ;

-- -----------------------------------------------------
-- Table `projecto_duo_db`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`cursos` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'guarda los cursos\nejemplos:\nmatematica_1\nlogica_1\netc.....';


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipo_de_usuario` VARCHAR(45) NULL DEFAULT 'estudiante' COMMENT 'puede ser\nadministrador\nestudiante\nusuario\n',
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`cursos_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`cursos_usuarios` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`cursos_usuarios` (
  `cursos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  INDEX `fk_cursos_estudiantes_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_cursos_estudiantes_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_cursos_estudiantes_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `projecto_duo_db`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_estudiantes_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `projecto_duo_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`capitulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`capitulos` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`capitulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `numero` INT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_capitulos_cursos1_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_capitulos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `projecto_duo_db`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`preguntas` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capitulos_id` INT NOT NULL,
  `pregunta` VARCHAR(45) NULL COMMENT 'que es html?',
  `opciones` VARCHAR(256) NULL COMMENT 'un lenguaje,  una comida, un show de television',
  `respuesta` VARCHAR(45) NULL COMMENT 'un lenguaje',
  PRIMARY KEY (`id`),
  INDEX `fk_ejercicios_capitulos1_idx` (`capitulos_id` ASC),
  CONSTRAINT `fk_ejercicios_capitulos1`
    FOREIGN KEY (`capitulos_id`)
    REFERENCES `projecto_duo_db`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`estudiante-respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`estudiante-respuestas` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`estudiante-respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `respuesta` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  `preguntas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante-respuestas_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_estudiante-respuestas_ejercicios1_idx` (`preguntas_id` ASC),
  CONSTRAINT `fk_estudiante-respuestas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `projecto_duo_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante-respuestas_ejercicios1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `projecto_duo_db`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projecto_duo_db`.`preguntas_de_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projecto_duo_db`.`preguntas_de_seguridad` ;

CREATE TABLE IF NOT EXISTS `projecto_duo_db`.`preguntas_de_seguridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(45) NULL COMMENT 'como se llama tu mama?',
  `respuesta` VARCHAR(45) NULL COMMENT 'mamita',
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_de_seguridad_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_preguntas_de_seguridad_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `projecto_duo_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `projecto_duo_db`.`cursos`
-- -----------------------------------------------------
START TRANSACTION;
USE `projecto_duo_db`;
INSERT INTO `projecto_duo_db`.`cursos` (`id`, `nombre`) VALUES (1, 'matematicas');
INSERT INTO `projecto_duo_db`.`cursos` (`id`, `nombre`) VALUES (2, 'logica');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projecto_duo_db`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `projecto_duo_db`;
INSERT INTO `projecto_duo_db`.`usuarios` (`id`, `nombre`, `apellido`, `tipo_de_usuario`, `usuario`, `clave`, `cedula`) VALUES (1, 'admin', 'admin', 'admin', 'administrador', 'clave', NULL);
INSERT INTO `projecto_duo_db`.`usuarios` (`id`, `nombre`, `apellido`, `tipo_de_usuario`, `usuario`, `clave`, `cedula`) VALUES (2, 'maestro', 'maestro', 'maestro', 'maestro', 'clave', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `projecto_duo_db`.`cursos_usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `projecto_duo_db`;
INSERT INTO `projecto_duo_db`.`cursos_usuarios` (`cursos_id`, `usuarios_id`) VALUES (1, 1);
INSERT INTO `projecto_duo_db`.`cursos_usuarios` (`cursos_id`, `usuarios_id`) VALUES (2, 1);
INSERT INTO `projecto_duo_db`.`cursos_usuarios` (`cursos_id`, `usuarios_id`) VALUES (1, 2);
INSERT INTO `projecto_duo_db`.`cursos_usuarios` (`cursos_id`, `usuarios_id`) VALUES (2, 2);

COMMIT;

